### PR TITLE
Add WorldGuard `friendly-fire` flag

### PR DESCRIPTION
**Pull request by szumielxd**
Well... Simple WG flag (`fg-friendly-fire`) to allow players in the same guild (or allies) to damage each other regardless of their pvp setting. I think It's usefull for e.g. mass pvp events, or duels, where every player should be able to damage everyone, even his own guild-mates.

### CODE REVIEW

**Comment by P3ridot** [comment]
We don't add features to FG 4.0. Now it's only for bug fixes. PRs should be created to 5.x branch where we're currently adding new features

**Comment by szumielxd** [comment]
As much as I hate to admit it, the best server version for 1.8 client environment is... 1.8.
But yeah, I understand. Thanks for the reply!

**Comment by P3ridot** [comment]
> We don't add features to FG 4.0. Now it's only for bug fixes. PRs should be created to 5.x branch where we're currently adding new features

Nevermind - We decided to accept this PR
I merged latest 4.x changes and fixed check for region (to not break friendly-fire protection if there is no WG hook)

**Comment by P3ridot** [comment]
Also changed from boolean type to enum type which also provide option to disable friendly fire in specific regions

**Review by P3ridot — APPROVED** [review]

**Pull request merged**
