### PR TITLE
GH-1706 Add ability to fill and pour buckets on guild regions

### LINKED ISSUE #1706: Waterskille
Dać Możliwość graczom spoza gildii rozlewanie wody na terenie wrogiej gildii

### PR DESCRIPTION
**Pull request by Inder00**
Fixes #1706

### CODE REVIEW

**Comment by ticzuu** [comment]
eeee

**Review by ticzuu — COMMENTED** [review]
zostalem tutaj dodany bez permisji

**Comment by Inder00** [comment]
To the moon 🚀

**Review by dzikoysk — APPROVED** [review]

**Comment by Inder00** [comment]
:shipit:

**Pull request merged**
